version: '3'

services:
  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: php-service
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db
  
  # Web Server (NGINX)
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: webserver
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - app
  
  # Database (optional)
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: your_laravel_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db-data: